create table if not exists public.books
(
    id integer generated by default as identity
        primary key,
    isbn   varchar(16) not null,
    title  varchar(128),
    author varchar(64),
    price  numeric(6, 2)
);